# -*- coding:utf8 -*-
"""
Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

first = FIRST = 1
second = SECOND = 2
fibonacci = [FIRST, SECOND, ]
cur_val = 0
while cur_val < 4000000:
    fibonacci.append(cur_val)
    cur_val = first + second
    first = second
    second = cur_val

total = 0
result = [val for val in fibonacci if val % 2 == 0]
for val in result:
    total += val
print(total)
