# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_auto_20170814_2021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choide',
            new_name='Choice',
        ),
    ]
